ROOT_DIR=$(pwd)
SRC_DIR="$ROOT_DIR/src"
BUILD_DIR="$ROOT_DIR/build"

mkdir -p "$BUILD_DIR"

echo "============================================"
echo "  Bai 4: The access modifier trap"
echo "============================================"
echo ""
echo "--- Truoc khi sua: (KHONG co public) ---"
echo ""
echo "Code loi:"
echo "  class DataManager implements IData {"
echo "      void show() {  // <-- thieu public"
echo "          System.out.println(\"Show Data\");"
echo "      }"
echo "  }"
echo ""
echo "Bien dich..."
javac -d "$BUILD_DIR" "$SRC_DIR/IData.java" "$SRC_DIR/DataManagerBefore.java" 2>&1
echo ""
echo "--- Sau khi sua: (CO public) ---"
echo ""
echo "Code dung:"
echo "  class DataManager implements IData {"
echo "      @Override"
echo "      public void show() {  // <-- da co public"
echo "          System.out.println(\"Show Data\");"
echo "      }"
echo "  }"
echo ""
echo "Bien dich va chay..."
javac -d "$BUILD_DIR" "$SRC_DIR/IData.java" "$SRC_DIR/DataManagerAfter.java" "$SRC_DIR/Main.java" && java -cp "$BUILD_DIR" Main
